all: calculator madlib shape var

calculator: Calculator.c
	clang Calculator.c -o calculator

madlib: madLib.c
	clang madLib.c -o madlib

shape: shape.c
	clang shape.c -o shape

var: var.c
	clang var.c -o var

clean:
	rm *.o calculator madlib shape var
